### ISSUE TITLE
writeInterval default setting

### ISSUE THREAD

**Issue by AllanHodkinson** [amekkawi/cwlogs-writable#21]
Hi Andre,
Not an issue per se but I was wondering how the default setting of the writeInterval as `process.nextTick` actually works in practice if many log requests are made per second, given that PutLogEvents() is throttled at 5 requests per second per log stream. Looking at the code the ThrottlingException error isn't handled yet so the error would fall through to next() (unless a custom handler is used to reschedule the upload)?  Would setting writeInterval to 200mS act as a throttle to the request rate so the 5 request per second limit would never be hit?
Many thanks,
Allan

**Comment by amekkawi** [comment]
Hi Allan,

Originally I was creating this library as a drop in replacement for bunyan-cloudwatch so I think that is what I took this approach. I did feel the same way though so maybe it's better I reevaluate the `writeInterval` behavior.

From testing I've seen that the AWS SDK (used by this library) will retry a few times on ThrottleExcepion on its own before it gives up and this library would get the throttle error. I think the SDK adds a wait timer when it's retrying in it's own.

Let me do some load testing to see what might work best.

To answer your question though, you could set a wait timer of 200ms and it should be fine but you may want to use the custom error handling at https://github.com/amekkawi/cwlogs-writable/blob/master/README.md#recovering-from-errors and add your own timer on ThrottleException.

I'm going to take a look at #1 again too.

**Comment by AllanHodkinson** [comment]
Hi Andre,
Thanks for the reply.  We have had some issues using bunyan-cloudwatch with throttling and also upload sizes being exceeded so do intend to switch over to your module in the future.  
I don't know what the resolution of the measurement used to enforce AWS 5 request/second limit is, we may still see throttling with a 200mS writeInterval so handling the exception makes sense.
Cheers.

**Comment by amekkawi** [comment]
Using the custom error callback is definitely the way to go. In our production use of cwlogs-writable I always attempt to recover from errors.

Instead I'll do a few things:

1. When errors happen consecutively, I'll add an increasing timeout before calling `next` to try sending the logs again. You may want to do this instead of setting `writeInterval`.
2. If I hit a maximum number of consecutive errors, I write the queued logs to a file, and then call `next` with no arguments so that the logs will no longer be attempted to be sent but the logger will still continue to try to send logs.

We were getting network errors in our EC2s recently (related to DNS problems) so I decided to always retry on error, instead of trying to determine which errors to retry on.

Let me know if you have any other questions.
