### ISSUE TITLE
Uncaught InvalidSequenceTokenException

### ISSUE THREAD

**Issue by oliversalzburg** [amekkawi/cwlogs-writable#8]
After including this module in our project, our application keeps crashing due to `InvalidSequenceTokenException: The given sequenceToken is invalid.`.

This was addressed in bunyan-cloudwatch: https://github.com/mirkokiefer/bunyan-cloudwatch/pull/23

Looking at your code, I did not see where the potential for this error is coming from.

**Comment by amekkawi** [comment]
This error typically happens when more than one process/thread/etc is pushing log events to the same CloudWatch Log Stream name.

Ideally you want each process to have a unique Log Stream name and then view/search/etc the log events at the Log Group level instead. As I recall the AWS docs aren't very clear on this.

In mirkokiefer/bunyan-cloudwatch#23 they addressed this by just describing the stream to get the correct sequence token.

However, this is fixing the symptom instead of the problem. The default limit for the DescribeLogStream call (which gives you the next sequence token) has a default limit of 5 per second per account per region. It can be increased but this represents an actual limit that could quickly be reached making it a risk to scalability.

Once that limit is reached the DescribeLogStream calls will get throttled and since this is per account/region this could cause issues throughout applications and be very difficult to detect.

If the approach is to make the Log Stream names as unique as possible, you will not encounter scaling issues because there is no limit on the number of Log Streams per Log Group and no limit on creating the Log Streams.

I'm going to review the cwlogs-writable docs to make this approach more obvious.

See http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html for the limits for CloudWatch Logs.

Let me know your thoughts. I'm going to post a comment to the bunyan-cloudwatch PR to point out this issue and see what the author thinks as well.

**Comment by oliversalzburg** [comment]
Some very good points indeed. Sadly, I've also since come to the conclusion that our whole approach to logging was wrong and we're not going a different route. Let me elaborate.

We use ECS to run our Docker images. Docker provides the awslogs driver, which allows us to log more or less directly into CloudWatch. This is great. But I always missed the ability to see all the logs of all instances of a certain process in a single view.

So we stopped logging to stdout and used bunyan-cloudwatch to send everything to the same stream. This was awesome (in testing, where we only ran a single worker). Needless to say, we realized the concurrency issue soon after and started looking in all the wrong places.

It was not clear to me that the problem is multiple writers to the CloudWatch log stream **name**. *I* thought the problem was having multiple `aws-sdk` instances in your single process and having them write to CloudWatch. Obviously, this is not the case.

When I realized this, I also came across an AWS forum post that basically said not to write to the same stream name from multiple workers and to **use the Search Log Group button** to see all streams in a combined view. I had no clue that that is what that button would do.

Alright, so then I just went back to writing my bunyan raw JSON output to stdout and capturing it with awslogs.

To conclude, I fully agree with your reasoning that the approach used by bunyan-cloudwatch is not a proper fix and the whole problem only came up because we were not doing it the right way.

Cheers :)

**Comment by amekkawi** [comment]
That's interesting. Sorry to hear it didn't work out for you!

I've handled it by including metadata in the bunyan log records so I can filter within the Log Group.

Since we're using node cluster when I create my per-process logger it looks a bit like this:

```
bunyan.createLogger({
    name: '<instance-id>', // something like "prod" or "p-1"
    proc_name: 'worker', // in our app this would also be "master", "job" or "cli",
    proc_group: '123456789' // see below
})
```

In the entry node script I set an environmental variable (that all child processes will inherit) of a unique ID that will make it's way into proc_group. That way when the entire server is restarted I can distinguish the logs from before/after the restart.

The LogStream names end up something like `prod-123456789-worker-P123`, where `P123` is the process pid.
